name: HeraCore
version: '${project.version}'
main: fr.whitefox.heracore.Main
authors: [ WhiteFox ]
description: Hera is a utility plugin supporting different modules allowing for example community event management, better server security, integration with Discord, and more.
website: https://github.com/whitefox2232

commands:
  tpall:
    description: Commande permettant de tp l'entièreté du serveur sur la position de l'executeur
    permission: hera.tpall
  dupeip:
    description: Get IP address of a Player
    permission: hera.dupeip
  vanish:
    description: Devenez invisible !
    permission: hera.vanish
  gm:
    description: Permet de changer votre mode de jeu
    permission: hera.gm
  heal:
    description: Permet de vous régénérer
    permission: hera.heal
  feed:
    description: Permet de remettre votre niveau de nourriture au maxiumum
    permission: hera.feed
  spawn:
    description: Revenir au spawn
    permission: hera.spawn
  rain:
    description: Permet de mettre de la pluie
    permission: hera.weather
  thunder:
    description: Permet de mettre de l'orage
    permission: hera.weather
  sun:
    description: Permet de clear la pluie et l'orage
    permission: hera.weather
  freeze:
    description: Permet de freeze un joueur
    permission: hera.freeze
  fly:
    description: Permet de se mettre en fly
    permission: hera.fly
  day:
    description: Permet de définir le monde sur jour
    permission: hera.time
  night:
    description: Permet de définir le monde sur nuit
    permission: hera.time
  kick:
    description: Permet d'éjecter un joueur du serveur
    permission: hera.kick
  pday:
    description: Permet de définir la vision du joueur sur jour
    permission: hera.time
  pnight:
    description: Permet de définir le vision du joueur sur nuit
    permission: hera.time
  ban:
    description: Permet de bannir temporairement ou définitivement un joueur
    permission: hera.ban
  unban:
    description: Permet de débannir un joueur
    permission: hera.ban
  mute:
    description: Permet de mute un joueur
    permission: hera.mute
  unmute:
    description: Permet d'unmute un joueur
    permission: hera.mute
  inf:
    description: Donne les informations générales d'un joueur
    permission: hera.inf
  history:
    description: Permet d'obtenir l'historique d'un joueur
    permission: hera.history
  warn:
    description: Permet d'avertir un utilisateur
    permission: hera.warn
  back:
    description: Permet de revenir sur son dernier point de mort
    permission: hera.back
  home:
    description: Vous permet de vous téléporter à un point prélablement enregisté
    permission: hera.home
  homes:
    description: Vous permet de savoir vos points de téléportation existants
    permission: hera.home
  sethome:
    description: Vous permet de vous créer un point afin de vous y téléporter ultérieurement
    permission: hera.home
  delhome:
    description: Vous permet de supprimer un point de téléportation
    permission: hera.home
  setspawn:
    description: Permet de définir le point de spawn
    permission: hera.setspawn
  shutdown:
    description: Arrête le serveur
    permission: hera.shutdown
  antivpn:
    description: Permet de paramettrer l'anti-vpn
    permission: hera.antivpn